### ISSUE TITLE
Talk Proposal: Build RestAPI with NodeJS and GitHub CodeSpaces

### ISSUE THREAD

**Issue by blacky-yg** [BarcelonaJS/events#12]
### Description

Join us for a talk on how to build a RestAPI with NodeJs and GitHub CodeSpaces. You will learn how to use GitHub CodeSpaces to develop and deploy your NodeJS app quickly and easily, and how to use it to create a powerful and reliable RestAPI. We will discuss the basic concepts of NodeJS, how to use GitHub CodeSpaces to manage your project, and how to use the Express framework to build your RestAPI. We will also show how to use the GitHub CodeSpaces API to automate your project deployment. Finally, we will discuss best practices for using GitHub CodeSpaces to build and manage your applications. This is an excellent opportunity to learn how to use GitHub CodeSpaces to build powerful and reliable RestAPI with NodeJS.

Don't miss out on this great opportunity!
It can take 30min or 40min.

### Social Networks
[Twitter](https://twitter.com/blacky_yg)
[LinkedIn](https://www.linkedin.com/in/hamidou-tessilimi/)
[WebSite](https://www.hamidoutessilimi.me/)

### Code of Conduct

- [x] I've read and agree to the
      [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by onedesert** [comment]
Hi! The next meetup will be on the 23rd of march, will you be available to present by then? also, the max. time is between 25-30 min (including Q&A)

Thanks!

**Comment by blacky-yg** [comment]
Hello,

Yes, I will be available to present on this day.

Thank you

[photo]<http://www.epitech-it.es/>
Hamidou TESSILIMI
Student in 4th year, Epitech Barcelona/Spain
***@***.******@***.***>
www.epitech.es<http://www.epitech-it.es/>
Carrer Joan Miró 21, 08005 Barcelona, España



De : Yann Torres ***@***.***>
Date : vendredi, 3 mars 2023 à 11:38
À : BarcelonaJS/events ***@***.***>
Cc : Hamidou Tessilimi ***@***.***>, Author ***@***.***>
Objet : Re: [BarcelonaJS/events] Talk Proposal: Build RestAPI with NodeJS and GitHub CodeSpaces (Issue #12)

Hi! The next meetup will be on the 23rd of march, will you be available to present by then? also, the max. time is between 25-30 min (including Q&A)

Thanks!

**Comment by onedesert** [comment]
Perfect! Thanks.

**Comment by onedesert** [comment]
The event is already published [here](https://www.meetup.com/BarcelonaJS/events/292064668/) see you next week, we are looking forward to your talk!

**Comment by onedesert** [comment]
@blacky-yg are you ready for today? please come 10 min early so we can setup the presentation. See you there!

**Comment by blacky-yg** [comment]
@onedesert yes,I will be there
