### ISSUE TITLE
Talk Proposal: Growing and maintaining speed as an FE while your team doubles

### ISSUE THREAD

**Issue by pransh15** [BarcelonaJS/events#13]
Filling this in for Fredrik S. Oseberg, Principal Engineer at Unleash.

### Description
As a Principal Engineer with over 10 years of experience, I’d like to talk about learnings that we have made about the quality of the codebase over the years. What does quality code really looks like and how to make it readable. When it is readable, how does it make it easy for you to setup for success and your company. These are the steps you need to be aware of as your team grows, and how to collaborate in a way that makes sense.

Join in for years of learning, in a single talk.

### Social Networks
[Twitter](https://twitter.com/foseberg)
[LinkedIn](https://www.linkedin.com/in/foseberg/)

### Code of Conduct

- [x] I've read and agree to the
      [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by pransh15** [comment]
🔔 Ping!
I know there's no promise on when issues will be answered, but I was hoping for a response here.

**Comment by onedesert** [comment]
Hi! Thank you for your patience. Our next meetup will be the 23rd of March, we have another talk line up for that, but yours is the second if the first speaker can make it. In 5 days, we try to confirm an otherwise follow with you.

Just remind that talks have to last between 25–30 minutes total.

Thanks.

**Comment by pransh15** [comment]
Hey @onedesert, can you please share a tentative date so that I can confirm availability?

**Comment by onedesert** [comment]
So far, the last two months of the week, we would narrow more as soon as we close with the venue sponsor.

**Comment by pransh15** [comment]
I see, the last two weeks have KubeCon EU and another meetup in Oslo. Can we move this to May/June then?

**Comment by onedesert** [comment]
Sure, we keep this issue open and for every month we will ask you. Keep in mind that usually is the last week of the month, or sometimes second to last.

**Comment by pransh15** [comment]
Sounds good, thanks @onedesert! 👍

**Comment by onedesert** [comment]
Hello! We are scheduling this month's meetup, the sponsor can host on the 17th of May (this month).

We are asking you among the 3 oldest applications, and we are waiting until Thursday to assign the talk.

Please let us know if you can give your talk that day. Thanks!

**Comment by onedesert** [comment]
We are closing this talk due to inactivity, please reopen if you would like to participate in future events. Thanks.
