### ISSUE TITLE
Sponsor Request: Unleash

### ISSUE THREAD

**Issue by pransh15** [BarcelonaJS/events#14]
Hey!

I'm Pranshu, OSS Community Manager at [Unleash](https://getunleash.io). We are looking to sponsor meetups to get feedback from devs, and see if they would like to contribute to our product or any of the SDKs. Would love to see if it's a great fit with BarcelonaJS!

### Code of Conduct

- [x] I've read and agree to the [Code of Conduct](https://berlincodeofconduct.org)

**Comment by dmitry-zaets** [comment]
Hi!
Please provide some information about the venue.
Here you can find a list of sponsor requirements: https://github.com/BarcelonaJS/organization/blob/main/guidelines/monthly.md#sponsor-requirements

**Comment by onedesert** [comment]
@pransh15 are you still interested in sponsoring an event? Otherwise, we will close this issue. Thanks!

**Comment by dmitry-zaets** [comment]
Closed for inactivity. Please re-open if you are still interested in sponsoring the event.
