### ISSUE TITLE
Talk Proposal: Internacionalization (i18n) in Next.js

### ISSUE THREAD

**Issue by aralroca** [BarcelonaJS/events#15]
I have planned to conduct a presentation on Internationalization (i18n) in Next.js. The presentation will address the critical steps in adapting web applications to meet the linguistic and cultural requirements of a global audience. The advantages of early implementation of i18n in the development process and overcoming the challenges of translation will be discussed.

The objective of the presentation is to facilitate the configuration process of i18n applications in Next.js, address common issues, and provide an overview of the [next-translate](https://github.com/aralroca/next-translate) library for efficient translation management.

**Comment by onedesert** [comment]
Thanks for your summit, we will take it into account for future events. The next month, March, looks already booked, but could make it into Aprils.

Thanks again!

**Comment by onedesert** [comment]
We hope you're doing well! We're currently scheduling talks for the upcoming month of April, and we'd like to check if you'd be available and interested in presenting your talk during that time.

Please note that we're reaching out to all available talks, and we'll be selecting them based on chronological order of submission. If April works for you, kindly let us know, and we'll happily include your talk in our schedule if it fits within the line-up. Please, we would need a response within this week, thanks.

If you have any questions or need assistance, feel free to reach out.

Looking forward to your response!

**Comment by aralroca** [comment]
I'm interested in April, it's fine with me. I would like to know what day it is to ensure my availability.

**Comment by onedesert** [comment]
Thanks, we will get back to you as soon as we close some dates with the sponsor.

**Comment by onedesert** [comment]
Hi, we have finally a date for this month's meetup. It will be the next 25th of April at Travelport offices.

Please let me know if it still works for you, we are asking for the 3 available talks, and we will assign by issue age. We will confirm in 2 days or as soon as the oldest issue will reply.

Thanks!

**Comment by aralroca** [comment]
Yes, 25th April is fine for me 😊

**Comment by onedesert** [comment]
Perfect, as it's the oldest issue, you are confirmed as the community speaker for this month's event.

Please let us know if we can help you with anything, and be at the venue 5 minutes before to test your laptop connection etc ...

Looking forward and thank you!
