### ISSUE TITLE
Talk Proposal: React State Management Without Dependencies

### ISSUE THREAD

**Issue by antonkalik** [BarcelonaJS/events#16]
**Duration of talk**
15 mins

**Description**
The talk about how to create global state management in React applications without side dependencies and unnecessary re-rendering actions. We gonna go through store creation function, will solve the global state management problem without any boilerplate code or unnecessary re-rendering. Will cover usage of hook useSyncExternalStore and synchronize our store with our React application’s state. Will connect our global store’s values across the entire application.

**Talk Plan**
1. What the problem with state
2. Application structure and what we going to build
3. Will create some components and check what re-render
5. Create store
6. Will check how components updated
7. Upgrade store and why we need listeners 
8. Server side rendering 
9. Conclusion

**Contacts**
Github: https://github.com/antonkalik
LinkedIn: https://www.linkedin.com/in/antonkalik/
Twitter: https://twitter.com/idedycom

### Code of Conduct

- [x] I've read and agree to the
      [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by onedesert** [comment]
Thanks for your summit, we will take it into account for future events. The next month, March, looks already booked, but could make it into Aprils.

Thanks again!

**Comment by onedesert** [comment]
Hello! We are scheduling this month's meetup, the sponsor can host on the 17th of May (this month).

We are asking you among the 3 oldest applications, and we are waiting until Thursday to assign the talk.

Please let us know if you can give your talk that day. Thanks!

**Comment by onedesert** [comment]
We are closing this talk due to inactivity, please reopen if you would like to participate in future events. Thanks.
