### ISSUE TITLE
Talk Proposal: From multi-repo to mono-repo, from monolith to micro-frontend

### ISSUE THREAD

**Issue by fernandonino** [BarcelonaJS/events#18]
From multi-repo to mono-repo, from monolith to micro-frontend

by Weronika Olejniczak
Frontend developer @ [Lodgify](www.lodgify.com)

The presentation will describe, focusing on the technological path we followed, the journey that brought us from having only one monolith React application divided into more than 3 repositories to an orchestra of multi-micro frontend React applications, stored and built in one singular monorepo.

We will describe how we included all the different parts of our software in only one repository; how we moved from very slow Webpack configuration build systems to super-fast builds with esbuild, as well as the decision to stop publishing npm packages and to start uploading our bundles directly to Google Cloud Storage and serve them with configurable and flexible CDN. Finally, we will touch on the concept of commit environments and what will be the future iteration of our system.

### Code of Conduct

- [X] I've read and agree to the
      [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by dmitry-zaets** [comment]
Thanks for your proposal. The following month is already booked, so we've added you to the queue and would consider planning future events.

Thanks again!

**Comment by onedesert** [comment]
The event is already published [here](https://www.meetup.com/BarcelonaJS/events/292064668/) see you next week, we are looking forward to your talk!
