### ISSUE TITLE
Talk Proposal: The whys and hows of server-side rendering

### ISSUE THREAD

**Issue by zemlanin** [BarcelonaJS/events#19]
**The whys and hows of server-side rendering**

Anton Verinov, Developer at [Nebula](https://nebula.tv)

The talk will cover a short history of SSR at Nebula, why we needed it, how we did it, and what shortcuts we took to ship something good without spending time chasing the perfection

_The talk will be based on the [three-part series of blog posts](https://zemlan.in/ssr-backstory.html) (the last part, about interacting with CDNs, is in the drafts), **but it would be better not to link to it from meetup’s site before the event**_

- About me: [anton.click](https://anton.click)
- Mastodon: [@zemlanin@devua.club](https://devua.club/@zemlanin)

### Code of Conduct

- [x] I've read and agree to the
      [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by zemlanin** [comment]
April or May would be okay

**Comment by onedesert** [comment]
Hi, we have finally a date for this month's meetup. It will be the next 25th of April at Travelport offices.

Please let me know if it still works for you, we are asking for the 3 available talks, and we will assign by issue age. We will confirm in 2 days or as soon as the oldest issue will reply.

Thanks!

**Comment by zemlanin** [comment]
But if two other proposals are also available for the April meetup, I'm okay postponing mine to May

**Comment by onedesert** [comment]
Hi! Thanks for your prompt reply, the oldest issue already replied, and we had confirmed. Thanks for your comprehension, and we keep you for the May meetup.

Thanks again!

**Comment by onedesert** [comment]
Hello! We are scheduling this month's meetup, the sponsor can host on the 17th of May (this month).

We are asking you among the 3 oldest applications, and we are waiting until Thursday to assign the talk.

Please let us know if you can give your talk that day. Thanks!

**Comment by zemlanin** [comment]
Hi. I can

**Comment by dmitry-zaets** [comment]
Great, then scheduling for 17th of May
