### ISSUE TITLE
Talk Proposal: TS.ed plus Prisma 

### ISSUE THREAD

**Issue by felix210782** [BarcelonaJS/events#23]
Hi,

I would like to give a talk on two subjects: Prisma and TS.ed. My presentation will include tools for both and some code examples. While I already have a Prisma presentation, I'm really excited to present on TS.ed. https://tsed.io/getting-started/

### Code of Conduct

- [ X] I've read and agree to the
      [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by onedesert** [comment]
We have date for the next meetup, June 14th. Let me know if you can present at the event your talk.

Reminder: We propose to all active talks, by the end of tomorrow we will choose by summation date all the positive response. Thanks.

**Comment by felix210782** [comment]
I give you tonight an answer. I am not sure if i am in Barcelona at this
date.

Regards
Felix

www.kerberry.de
Kerberry GmbH
Im Buschgewann 26
69123 Heidelberg

Geschäftsführung: Felix Morillas Navas, Jasin Goldkorn
Sitz der Gesellschaft: Heidelberg
Handelsregister: Amtsgericht Mannheim HRB 744500


Am Do., 25. Mai 2023 um 12:23 Uhr schrieb Yann Torres <
***@***.***>:

**Comment by felix210782** [comment]
Sorry want make IT. I am Not in town in June

Regrads Felix

Felix Morillas Navas ***@***.***> schrieb am Do., 25. Mai 2023,
15:34:

**Comment by onedesert** [comment]
Hey there!

Would you be available to present your talk at our upcoming event hosted by Travelperk on the 17th of this month? We're reaching out to all open talk submissions, and will be assigning slots starting with the earliest responses received by the end of this week.

Looking forward to your reply!

**Comment by felix210782** [comment]
Hi

Really i am so sorry
I Will be Back at the18th to Barcelona from Work. I cannot make it.

RegardsFelix

**Comment by onedesert** [comment]
No problem, we keep you on the loop for future events. Thanks!

**Comment by onedesert** [comment]
Hello! We are reaching our again, now for the [November meetup](https://github.com/BarcelonaJS/events/issues/40) would happen on the 22nd, please let us know if you would be able to present, Thanks!!

**Comment by felix210782** [comment]
I will be there

Mit freundlichen Grüßen
Felix Morillas Navas

www.kerberry.de
Kerberry GmbH
Im Buschgewann 26
69123 Heidelberg

Geschäftsführung: Felix Morillas Navas, Jasin Goldkorn
Sitz der Gesellschaft: Heidelberg
Handelsregister: Amtsgericht Mannheim HRB 744500


Am Di., 17. Okt. 2023 um 09:36 Uhr schrieb Yann Torres <
***@***.***>:

**Comment by felix210782** [comment]
I will try to make the Presentation in 2 weeks and will send it to you.]
Mit freundlichen Grüßen
Felix Morillas Navas

www.kerberry.de
Kerberry GmbH
Im Buschgewann 26
69123 Heidelberg

Geschäftsführung: Felix Morillas Navas, Jasin Goldkorn
Sitz der Gesellschaft: Heidelberg
Handelsregister: Amtsgericht Mannheim HRB 744500


Am Di., 17. Okt. 2023 um 13:35 Uhr schrieb Felix Morillas Navas <
***@***.***>:

**Comment by onedesert** [comment]
Just to confirm, you will be ready to present the 22nd for sure, right? Thanks!

**Comment by felix210782** [comment]
Yes

**Comment by onedesert** [comment]
Hello @felix210782!

Are you ready to present? Can you please provide with a description of your talk so we can use the for event details?

Thanks!

**Comment by felix210782** [comment]
Hi Yann

I will be ready I will finish the presentation on friday I hope.
Talk about TS.ed
awesome server-side application plus prisma
I will make a small example

Details

   - Speaker Name: Felix Morillas Navas
   - Speaker Position: Data Scientist / Backend Developer
   - Speaker Company: Adesso Insurance Solutions GmbH
   - Speaker Twitter/Website: Only Linkdin
   https://www.linkedin.com/in/felix-morillas-navas-323107153/
   and my website www.kerberry.de


Regards
Felix Morillas Navas

www.kerberry.de
Kerberry GmbH
Im Buschgewann 26
69123 Heidelberg

Geschäftsführung: Felix Morillas Navas, Jasin Goldkorn
Sitz der Gesellschaft: Heidelberg
Handelsregister: Amtsgericht Mannheim HRB 744500


Am Di., 7. Nov. 2023 um 16:26 Uhr schrieb Yann Torres <
***@***.***>:

**Comment by onedesert** [comment]
Thanks!

**Comment by felix210782** [comment]
Hi,

please use another email adress
***@***.***

I will close this email account now

Attached find Prisma Presentation. But I will still at the TS.ED. I had to
much work this week and no time sorry
 Jungle Academy von Prisma
<https://docs.google.com/presentation/d/1LBiLhr9YLk7WqzyDyqdY8TU6m7wbJ4Du73ZZ8MvOnvs/edit?usp=drive_web>
I still need to translate it in English. I will make the presentation this
next week definitly.

And please use this ***@***.***
thanks

Regards
Felix Morillas Navas

www.kerberry.de
Kerberry GmbH
Im Buschgewann 26
69123 Heidelberg

Geschäftsführung: Felix Morillas Navas, Jasin Goldkorn
Sitz der Gesellschaft: Heidelberg
Handelsregister: Amtsgericht Mannheim HRB 744500


Am Mi., 8. Nov. 2023 um 10:43 Uhr schrieb Yann Torres <
***@***.***>:

**Comment by onedesert** [comment]
Hi, sorry, but the new email is being banned by GitHub and is not shown.

> And please use this ***@***.***

**Comment by felix210782** [comment]
Ok no problem

**Comment by felix210782** [comment]
SEe you today. Can i Bring also a friend
Mit freundlichen Grüßen
Felix Morillas Navas

www.kerberry.de
Kerberry GmbH
Im Buschgewann 26
69123 Heidelberg

Geschäftsführung: Felix Morillas Navas, Jasin Goldkorn
Sitz der Gesellschaft: Heidelberg
Handelsregister: Amtsgericht Mannheim HRB 744500


Am Sa., 18. Nov. 2023 um 17:52 Uhr schrieb Felix Morillas Navas <
***@***.***>:

> Ok no problem
>

**Comment by felix210782** [comment]
Attached find my presentation
Mit freundlichen Grüßen
Felix Morillas Navas

www.kerberry.de
Kerberry GmbH
Im Buschgewann 26
69123 Heidelberg

Geschäftsführung: Felix Morillas Navas, Jasin Goldkorn
Sitz der Gesellschaft: Heidelberg
Handelsregister: Amtsgericht Mannheim HRB 744500


Am Mi., 22. Nov. 2023 um 09:30 Uhr schrieb Felix Morillas Navas <
***@***.***>:

> SEe you today. Can i Bring also a friend
> Mit freundlichen Grüßen
> Felix Morillas Navas
>
> www.kerberry.de
> Kerberry GmbH
> Im Buschgewann 26
> 69123 Heidelberg
>
> Geschäftsführung: Felix Morillas Navas, Jasin Goldkorn
> Sitz der Gesellschaft: Heidelberg
> Handelsregister: Amtsgericht Mannheim HRB 744500
>
>
> Am Sa., 18. Nov. 2023 um 17:52 Uhr schrieb Felix Morillas Navas <
> ***@***.***>:
>
>> Ok no problem
>>

**Comment by onedesert** [comment]
Attachments does not work with Github comments
