### ISSUE TITLE
Talk Proposal: Remix - an introduction

### ISSUE THREAD

**Issue by MoSattler** [BarcelonaJS/events#24]
[Remix](https://remix.run) is a full stack web framework that lets you focus on the user interface and work back through web standards to deliver a fast, slick, and resilient user experience.

I would love to give an overview about what remix is, what it can do, and why IMHO remix should be one of the top choices for any new web app.

**About me**
I am Mo, full stack developer, who worked the last couple years as a consultant for early stage companies trying to get their product up and running. Before that I worked 5 years here in Barcelona at TravelPerk as an engineer.

GitHub: https://github.com/MoSattler
Twitter: https://twitter.com/Mo_Sattler
LInkedIn: https://www.linkedin.com/in/mo-s-8282971a0/

### Code of Conduct

- [X] I've read and agree to the [Code of Conduct](https://berlincodeofconduct.org)

**Comment by onedesert** [comment]
Hi,

Firstly, thanks for your submission. We are looking forward to hosting you at a future event.
How we work is using a speaker from the community and a speaker from the sponsor on the monthly events.
We have a line-up already for the next month's community speaker, we follow the chronological order of issue, and we ask the oldest 3 if they will be available.

We will contact you as soon as we have an available spot through this same issue, please let us know if you have any question, or you need any support.

Thanks.

**Comment by onedesert** [comment]
We have a date for the next meetup, June 14th. Please let me know if you can present at the event your talk.

Reminder: We propose to all active talks, by the end of tomorrow we will choose by summation date all the positive response. Thanks.
