### ISSUE TITLE
Talk Proposal: Hexagonal architecture with Typescript

### ISSUE THREAD

**Issue by arnaugris97** [BarcelonaJS/events#25]
It will be a talk about using hexagonal architecture with Typescript. I will explain what hexagonal architecture is, why it is useful for frontend developers, how we can use it together with TDD and show some success cases. We will see a way to build framework-agnostic apps, adding robustness and resilience.

### Code of Conduct

- [x] I've read and agree to the
      [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by dmitry-zaets** [comment]
Assigned to BarcelonaJS May as speaker from the sponsor
