### ISSUE TITLE
Sponsor Request: InnoIT

### ISSUE THREAD

**Issue by luisinnoit** [BarcelonaJS/events#27]
As I have discussed with Yann Torres, InnoIT would love to host an upcoming event (in September) in some of our offices in **Barcelona**.  We would also take care of the food and beverages, and promotion on our social media and meetup community with **more than 4,000 members and 90 organized tech meetups.**.

We are a native technology and digital consultant located in Spain, with more than 6 years of experience in projects and team management market covering the product development life cycle and software & web solutions. Build custom solutions for CEOs and CTOs across different business activities from abroad the world. We are a team of 140 IT professionals located in Barcelona and Madrid, providing support to more than 45 worldwide clients. 

Kind regards,

### Code of Conduct

- [X] I've read and agree to the [Code of Conduct](https://berlincodeofconduct.org)

**Comment by onedesert** [comment]
Thanks for the summiting your interest, we will reach out on future events (September) to start organizing.

**Comment by onedesert** [comment]
Please list your venue capacity?

**Comment by luisinnoit** [comment]
-	[Aticco Verdaguer](https://goo.gl/maps/rg42KJYz8CdUsHKs7): C/ de Provenza, 339 (max. 70) 
-	[Aticco Bogatell](https://goo.gl/maps/ewa8bRSQC5ZnFTFF6): C/ de Pallars 108 (max. 120)
-	[Aticco Urquinaona](https://goo.gl/maps/9xNLVqAEhFsTHzRB7): Rda. de Sant Pere, 52 (max. 70)

**Comment by luisinnoit** [comment]
Hi, the summer holydays are getting closer, and we are closing some dates, any news about this or if we can solve any more questions for you? Thanks

**Comment by onedesert** [comment]
First of all, thank you for your patience. Our team is currently on vacation and won't be back until September, so we haven't yet finalized a date. I will consult with the rest of the organizing team and inform you as soon as possible regarding the availability of sponsorship opportunities for September. In any case, our events typically take place toward the end of the month, and sponsors are given the option to choose a date.

Thanks again for your interest and understanding.

**Comment by onedesert** [comment]
@luisinnoit Please contact me on LinkedIn, so we can briefly chat to close details for this month's event https://www.linkedin.com/in/yann-torres/, thanks!

**Comment by onedesert** [comment]
@luisinnoit are you guys still interested in hosting a BarcelonaJS event? If so, November could work. Please connect with me on LinkedIn https://www.linkedin.com/in/yann-torres/ to proceed. Otherwise, we will close this issue next week, but you are free to reopen at anytime.

Thanks!

**Comment by luisinnoit** [comment]
> @luisinnoit are you guys still interested in hosting a BarcelonaJS event? If so, November could work. Please connect with me on LinkedIn https://www.linkedin.com/in/yann-torres/ to proceed. Otherwise, we will close this issue next week, but you are free to reopen at anytime.
> 
> Thanks!

Hi, yes, I am writing to you right now. Thanks

**Comment by onedesert** [comment]
Event already planning https://github.com/BarcelonaJS/events/issues/40
