### ISSUE TITLE
Talk Proposal: Serveless with Typescript how build it and survive

### ISSUE THREAD

**Issue by fredpalas** [BarcelonaJS/events#28]
I want to talk about serverless with typescript, from a practical perspective, when use it and who to use it, starting from coding, testing and deploying, will include some examples for backend and frontend.

### Code of Conduct

- [x] I've read and agree to the [Code of Conduct](https://berlincodeofconduct.org)

**Comment by onedesert** [comment]
We have a date for the next meetup, June 14th. Please let me know if you can present at the event your talk.

Reminder: We propose to all active talks, by the end of tomorrow we will choose by summation date all the positive response. Thanks.

**Comment by fredpalas** [comment]
June 14th I'm not in Barcelona.

So maybe next one on July.

Regards

**Comment by onedesert** [comment]
Thanks for your prompt response, we will get back on future events.

**Comment by onedesert** [comment]
Hey there!

Would you be available to present your talk at our upcoming event hosted by Travelperk on the 17th of this month? We're reaching out to all open talk submissions, and will be assigning slots starting with the earliest responses received by the end of this week.

Looking forward to your reply!

**Comment by fredpalas** [comment]
Hi,

I'm available for doing the talk.
