### ISSUE TITLE
Talk Proposal: What I learned as a developer from accidents in space

### ISSUE THREAD

**Issue by ai** [BarcelonaJS/events#29]
The space industry is very similar to software development. Human mistakes, a big project with a lack of communications, insane complexity. So there are a lot of things, which we can learn from them: not blame users, but change UI; report about issues in open source libraries; use linters. Especially, when all these best practices are wrapped in funny and real stories.

It will be a talk based on my article: https://evilmartians.com/chronicles/what-i-learned-as-a-developer-from-accidents-in-space

My Twitter: https://twitter.com/sitnikcode

### Code of Conduct

- [x] I've read and agree to the
      [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by onedesert** [comment]
We have a date for the next meetup, June 14th. Please let me know if you can present at the event your talk.

Reminder: We propose to all active talks, by the end of tomorrow we will choose by summation date all the positive response. Thanks.

**Comment by ai** [comment]
I will be ready for this date 👍

**Comment by onedesert** [comment]
Thanks! Your talk has been assigned to the June [Event](https://github.com/BarcelonaJS/events/issues/31)!
