### ISSUE TITLE
Talk Proposal: Future of colors in CSS: why I moved to oklch() from rgb(), hex, and hsl()

### ISSUE THREAD

**Issue by ai** [BarcelonaJS/events#3]
New CSS specifications are coming with powerful features for colors. Andrey Sitnik, the creator of PostCSS, will explain two features from new specs:
1. Native color transformations in CSS
2. New function `oklch()` to define colors in CSS

Twitter account: https://twitter.com/sitnikcode

### Code of Conduct

- [x] I've read and agree to the
      [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by dmitry-zaets** [comment]
Assigned to a November 2022 meetup
