### ISSUE TITLE
June 2023

### ISSUE THREAD

**Issue by onedesert** [BarcelonaJS/events#31]
### Details

- Where: Arbolus
- Address: [Gran Via de les Corts Catalanes 613](https://goo.gl/maps/btNPnzKBbnMKiAZc8)
- When: 2023-06-14
- Hosts: @dmitry-zaets , @onedesert 

### Agenda

- 19:00: Meet & Greet
- 19:15: [From Multiple Repositories to a Monorepo with NX](https://github.com/BarcelonaJS/events/issues/30)
- 19:40: Break
- 19:45: [What I learned as a developer from accidents in space](https://github.com/BarcelonaJS/events/issues/29)
- 20:10: Social

### Description

Details

Hello everyone! Join us for May's meetup, which will be held in Arbolus office. As always, we will have two talks followed by a networking session.
─────────────────────────────
From Multiple Repositories to a Monorepo with NX
by Lluc Estrany
Senior Software Engineer at Arbolus Technologies

In this talk, we will share our experience implementing NX, a robust build system that has positively impacted our development efficiency. We will explain the practical steps taken to integrate NX into our workflow, resulting in increased productivity, smoother collaboration, and faster project delivery.
─────────────────────────────
What I learned as a developer from accidents in space
by Andrey Sitnik https://twitter.com/sitnikcode

The space industry is very similar to software development. Human mistakes, a big project with a lack of communications, insane complexity. So there are a lot of things, which we can learn from them: not blame users, but change UI; report about issues in open source libraries; use linters. Especially, when all these best practices are wrapped in funny and real stories.
─────────────────────────────
IMPORTANT!
Security:

Access control: The security team requires an attendees list. Make sure you register for the event with your full name. Registration will close 24h before the event.
You’ll be asked to provide your name and ID (DNI, NIE, etc.) to access the building.
─────────────────────────────
After the talks, we'll have drinks and networking!

Are you interested in giving a talk or have a question? You are welcome to comment or shoot a meetup message to the organizers.

And don't forget to follow us on Twitter for the latest news [@BcnJS](https://twitter.com/BcnJS)
─────────────────────────────
Sponsor:

WIP

### Code of Conduct

We expect everyone to uphold our
[Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/),
so please take a minute to read through it.

**Comment by onedesert** [comment]
@ai @dmitry-zaets I'll prepare the event description and draft tonight. Who will be available to promote on twitter/linkedin? I can then sync with the [sponsor](https://github.com/BarcelonaJS/events/issues/22) so they promote it too.

**Comment by ai** [comment]
Twitter posts are on me (when we will have Meetup link, ping me in [DM in Telegram](t.me/sitnik)).

**Comment by onedesert** [comment]
Event published https://www.meetup.com/barcelonajs/events/293863266/
