### ISSUE TITLE
Sponsor Request: TravelPerk

### ISSUE THREAD

**Issue by robmosca** [BarcelonaJS/events#33]
Hi, my name is Roberto Mosca and I work as Principal Software Engineer at [TravelPerk](https://www.travelperk.com/), here in Barcelona. I have participated recently in one of the Meetups organized by BarcelonaJS, at Lodgify and I really liked the content, the organization and the general atmosphere of the event.

After talking about it with our team, we would like to host one of the next meetups in our [headquarter](https://www.travelperk.com/press-release/travelperk-unveils-new-post-pandemic-hq-in-center-of-barcelonas-vibrant-tech-district/) here in Barcelona (Carrer dels Almogàvers 160, 08018 Barcelona, Spain).

We offer to host the event, providing the venue, drinks and food.

Contextually to that, we would also like to offer a presentation about our recent migration to microfrontends, discussing our challenges and solutions.

### Code of Conduct

- [x] I've read and agree to the [Code of Conduct](https://berlincodeofconduct.org)

**Comment by robmosca** [comment]
We can accommodate up to 100 people and we would be ready to host either in July or September 2023.

**Comment by dmitry-zaets** [comment]
Thank you for submitting a sponsor request!
For the July meetup, we already have a sponsor, but we have no sponsor for September yet.

**Comment by robmosca** [comment]
Hi @dmitry-zaets, then we would be happy to host the September meetup! 🙂 What about the 13th or the 20th of September?

**Comment by dmitry-zaets** [comment]
Let's come back to the discussion in August. Usually, we plan the meetup 4-5 weeks in advance, as it's easier to plan everything close to the date.

**Comment by dmitry-zaets** [comment]
I've missed that we already have a sponsor for September (https://github.com/BarcelonaJS/events/issues/27).
So we can organize it in October if you want, or we will come back to you if the sponsor for September cancels their request.

**Comment by robmosca** [comment]
Understood. Sure. If September is already taken we will definitely host the one in October. And if the one of September cancels, we are happy to take that slot 🙂

**Comment by robmosca** [comment]
Hi @dmitry-zaets and @onedesert! It was great to host the event on July!
We would still like to have a chance at presenting our recent migration to microfrontends in one of the upcoming BarcelonaJS meetups. Do you think we could get a slot for a presentation?

**Comment by robmosca** [comment]
Sorry, what I meant is that we are still up to host the meetup in October, or later, and have a chance to present our recent migration to microfrontends at that event, if OK for you!

**Comment by robmosca** [comment]
We confirm we have availability on the 17th of October to host the meetup.

**Comment by onedesert** [comment]
Event plan already, @robmosca if Travelperk is open again to host us, please re-open this same issue.
