### ISSUE TITLE
Talk Proposal: Testing Strategy

### ISSUE THREAD

**Issue by Gpx** [BarcelonaJS/events#34]
Hi, I would like to give this talk at a future meetup. It's about what strategies I use to write FE tests and what are common issues and doubts new developers encounter when testing. It can be as long as 40 minutes, or I can trim it down to fit into 25.

### Code of Conduct

- [x] I've read and agree to the
      [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by onedesert** [comment]
Great to have you back @Gpx ! Most likely, we will need to keep the 2 talks format that will require the 25-min version. But maybe we can also run a special event.

How it works now is that on every month we host a sponsor and a community speaker. When we have the months' event sponsor, we ask everyone who posted a talk and by submit date we assign the community talk.

**Comment by Gpx** [comment]
Sounds good. Let me know when you have a slot 👍
