### ISSUE TITLE
Sponsor Request: Honeypot & New Work SE

### ISSUE THREAD

**Issue by itziarmerladet** [BarcelonaJS/events#35]
Honeypot is a developer-focused job platform. We constantly strive to bring value to the developer community and love both organizing and supporting any developer/tech-focused events. We have recently launched in Spain so we would love to sponsor any BarcelonaJS events. We are part of the New Work SE group, and have an office in Barcelona that has space for around 40 people, so we would be glad to host any of your events there. 

### Code of Conduct

- [X] I've read and agree to the [Code of Conduct](https://berlincodeofconduct.org)

**Comment by onedesert** [comment]
Thanks! We have collaborated before and would be a nice to do it again. We will start with monthly events again next September. I'll update though here are the months that we have sponsor availability, meanwhile you can add me on LinkedIn as it will be easier to communicate https://www.linkedin.com/in/yann-torres/.

**Comment by onedesert** [comment]
Hello @itziarmerladet we are looking a sponsor for the December event, would Honeypot be open to it?

**Comment by itziarmerladet** [comment]
I can check with the New Work office to see if its available. When would the event be? Do you have a date yet? Or any Thursday in December?

**Comment by itziarmerladet** [comment]
Hi Yann, 
It will be tricky for us the first 2 weeks due to vacation and an offsite in Berlin with the whole company, but we can look into it for the third week - perhaps December 21st?
I will check with New Work and get back to you.

**Comment by onedesert** [comment]
21th should work, please confirm so we can close sponsorship and speaker for December. Thanks!

**Comment by onedesert** [comment]
@itziarmerladet can we confirm the date and that Honeypot will sponsor the event for December? Thanks.

**Comment by itziarmerladet** [comment]
Hi Yann, sorry for the delay in getting back to you. I have been out of the office for the past 2 weeks and I am waiting for confirmation regarding our budget and availability of the office. Would any day that week work for you? (For example the 19th or 20th as well?). I will get back to you as soon as possible. I should get confirmation in the next days. 
Thanks!

**Comment by itziarmerladet** [comment]
Hi Yann. I have confirmed with the New Work office that we have availability on the 20th of December. Would this day work for you?

**Comment by onedesert** [comment]
Hello! Yes we can confirm that works for us too, I might not be there but @dmitry-zaets or @motanelu will.

**Comment by onedesert** [comment]
@itziarmerladet can you help me with the missing details here https://github.com/BarcelonaJS/events/issues/46?

**Comment by onedesert** [comment]
As the event has been confirmed we move the conversation there https://github.com/BarcelonaJS/events/issues/46
