### ISSUE TITLE
Talk Proposal: 10 things you can do with OCaml (as a TypeScript developer)

### ISSUE THREAD

**Issue by jchavarri** [BarcelonaJS/events#36]
[OCaml](ocaml.org/) is a pragmatic and robust typed programming language that shares unexpected similarities with JavaScript. This talk aims to introduce OCaml to TypeScript developers and highlight its practical applications. We'll explore its strengths, syntax, real-world use cases, and how to compile OCaml code into JavaScript using [Melange](https://melange.re/).

---

Can link to https://twitter.com/javierwchavarri, https://ocaml.org and https://melange.re.

### Code of Conduct

- [x] I've read and agree to the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by onedesert** [comment]
Hello! Thanks for your application, we will start with the monthly events on October, and we will soon reach out to schedule you on future events.

We appreciate your patience!

**Comment by jchavarri** [comment]
No problem, thanks for the heads up!

**Comment by onedesert** [comment]
Hey there!

Would you be available to present your talk at our upcoming event hosted by Travelperk on the 17th of this month? We're reaching out to all open talk submissions, and will be assigning slots starting with the earliest responses received by the end of this week.

Looking forward to your reply!

**Comment by jchavarri** [comment]
Hey @onedesert!

Sure, it will be possible to present the talk that day. If it gets confirmed, we can keep discussing more details about talk duration later on.

Thanks!

**Comment by onedesert** [comment]
@jchavarri thanks for your prompt response, unfortunately we can't count with your talk for this month's event.  https://github.com/BarcelonaJS/events/issues/28 replied too, and his issue summit is older than yours.

But we can pre-book you for the November event, although we don't have a fix date yet.

Thanks again!

**Comment by jchavarri** [comment]
No problem, there is no rush :) When you start planning for the November event please let me know so we can arrange it.

**Comment by onedesert** [comment]
Hello! We are reaching our again, now for the [November meetup](https://github.com/BarcelonaJS/events/issues/40) would happen on the 22nd, please let us know if you would be able to present, Thanks!!

**Comment by jchavarri** [comment]
Hi! yes, i would be ready, if the spot is still available.

**Comment by onedesert** [comment]
Thanks! For now, we have the community talk cover. I'm sorry, but I can assure that next talk you have the top priority. As we use issue date as a priority metric. For November, we might not have sponsor talk, so maybe you can jump in, otherwise let me know your availability for December as we have already a Sponsor almost available, and we will consider your availability to fit in.

**Comment by jchavarri** [comment]
No problem :)

> For November, we might not have sponsor talk, so maybe you can jump in

This might sound good, but I am not sure I fully understand it. Could you explain what sponsor talk is and what it would involve from my side please?

> otherwise let me know your availability for December as we have already a Sponsor almost available, and we will consider your availability to fit in.

I am available in December as well.

**Comment by onedesert** [comment]
Hi, foremost, thanks for your patience!

I mean that usually we have a community speaker (from those issues) and a sponsor speaker. For the next month maybe the sponsor does not provide one so we might have 2 community speakers. In that case you would be the second.

Hope is more clear no! Thanks!

**Comment by jchavarri** [comment]
Thanks for clarifying :) I will wait for the sponsor confirmation then, to know if the talk goes in November or December.

**Comment by onedesert** [comment]
Hello!

We got confirmation, and you can present at the December event, current details here https://github.com/BarcelonaJS/events/issues/46, let me know if it works for you.

Thanks!

**Comment by jchavarri** [comment]
Sounds good, thanks!

**Comment by onedesert** [comment]
Great! Thanks.
