### ISSUE TITLE
October 2023

### ISSUE THREAD

**Issue by dmitry-zaets** [BarcelonaJS/events#38]
### Details
- Company: Travelperk #33 
- Address: 
- When: 17th of October
- Hosts:
- Venue capacity:

### Agenda

- Meet & Greet
- Talk 1: https://github.com/BarcelonaJS/events/issues/39
- Break + Conference Tickets Ruffle
- Talk 2: https://github.com/BarcelonaJS/events/issues/28 
- Social

### Code of Conduct

We expect everyone to uphold our
[Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/),
so please take a minute to read through it.

**Comment by onedesert** [comment]
Added community speaker
