### ISSUE TITLE
December 2022

### ISSUE THREAD

**Issue by IagoLast** [BarcelonaJS/events#4]
### Details

- Company: www.veriff.com 
- Where: https://goo.gl/maps/NnEiihcHeRBLauWq9
- Address: Piso 9
- When: 2022-12-15
- Hosts: @Host1, @Host2
- Venue capacity: 50

### Talks
- #6 
- #7 

### Code of Conduct

We expect everyone to uphold our
[Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/),
so please take a minute to read through it.

**Comment by dmitry-zaets** [comment]
Assigned to a December 2022 meetup
