### ISSUE TITLE
Event: November 2023

### ISSUE THREAD

**Issue by onedesert** [BarcelonaJS/events#40]
### Details

- Where: [Aticco Verdager](https://maps.app.goo.gl/bFunbXVU3tH9bdHy9)
- Address: Carrer de Provença, 339, 08037 Barcelona
- When: 2023-11-22
- Hosts: @dmitry-zaets 
- Capacity: 70 pax.

### Agenda

- BarcelonaJS & Sponsor Intro (5 min each)
- Talk 1 (25min): https://github.com/BarcelonaJS/events/issues/50
- Break + ticket raffle
- Talk 2 (25min): https://github.com/BarcelonaJS/events/issues/23
- Social, food🍕 & drinks🧃!

### Code of Conduct

We expect everyone to uphold our
[Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/),
so please take a minute to read through it.

**Comment by onedesert** [comment]
Community talk assigned

**Comment by luisinnoit** [comment]
**InnoIT**

We are a technology and digital native consultancy based in Spain, with more than 6 years of experience in projects and market team management covering the product development lifecycle and software/web solutions.

We build custom solutions for CEOs and CTOs of different business activities around the world. We are a team of 200 people located in Barcelona and Madrid, supporting more than 45 clients worldwide.

Services we are experts in:

- Web Development
- Infrastructure & DevOps
- QA Testing & Test Automation
- Big Data & Machine Learning
- Methodologies: Agile, Lean, and Product Owner
- Hybrid low-code projects

We also have a large Meetup community in Barcelona and Madrid, with more than 3,000 members and 90 organized tech meetups.
