### ISSUE TITLE
Sponsor Request: Manychat

### ISSUE THREAD

**Issue by meowsphere** [BarcelonaJS/events#42]
### Description

Hi! I'm Anna from Manychat. We are building a Chat Marketing platform, and our company is 7 years old. We opened an office in Barcelona a year ago, started our first steps on integrating into the local IT community, and are now working on increasing our tech brand awareness among the Spanish IT market. We would love to collaborate to have a chance of building connection with Barcelona JS devs.

- [x] I've read the [event guidelines](https://github.com/BarcelonaJS/organization/blob/main/guidelines/monthly.md)
- [x] We bring a speaker too. Topic: "CI/CD observability for Frontend”

### Details

- Company Twitter: https://twitter.com/ManychatTech
- Company Website: https://manychat.com/
- Venue location: Our office at WeWork Paseo de Gracia: Passeig de Gràcia, 17, 08007 Barcelona (7th floor)
- Venue capacity: 50 people

### Code of Conduct

- [x] I've read and agree to the [Code of Conduct](https://github.com/BarcelonaJS/organization/blob/main/code-of-conduct.md)

**Comment by onedesert** [comment]
Hello!

Firstly, thanks for the interest. We have already closed sponsorship for next month, and December looks like it is almost closed too.

We can plan for the January event or wait if December's sponsor confirms during this week.

What you can already start is submitting [here](https://github.com/BarcelonaJS/events/issues/new?assignees=&labels=Talk%3A+Feature+%3Acinema%3A&projects=&template=talk-feature.md&title=Talk+Proposal%3A+%3Ctalk+title%3E) the talk, same procedure as for submitting sponsorship.

Thanks!

P.S: You can add me on linkedin too, so we have a quicker channel to sync for the event organization.

**Comment by dmitry-zaets** [comment]
Related Speaker: https://github.com/BarcelonaJS/events/issues/48

**Comment by onedesert** [comment]
Related Event: https://github.com/BarcelonaJS/events/issues/47

**Comment by onedesert** [comment]
Event is out there closing this sponsor. @meowsphere for future sponsor request we now use https://github.com/BarcelonaJS/event-sponsors/issues/new/choose
