### ISSUE TITLE
Talk Proposal: My experience on building a Super App with Quasar.js

### ISSUE THREAD

**Issue by imvenx** [BarcelonaJS/events#45]
### Description

I want to share my expierence building Arcanepad an ecosystem that consists of a super app or platform, sdk's, quasar+vue+electron.js, why I decided to go for native android and implement my own webview instead of capacitor.js, the architecture behind this, the intrincate communication system simplified with websockets, and how I'm reusing code between android web and desktop apps.

### Details

- Speaker Name: Vera
- Speaker Position: Software Developer
- Speaker Company: confidential
- Speaker Twitter/Website: [Twitter](https://twitter.com/arcanepad) [Web](https://arcanepad.com/#/) [Barcelona Game Creators Talk 23-oct:](https://www.youtube.com/watch?v=gBPPyrQ7Ya4)

### Other

I don't need help but It'd be nice having feedback before the event.

### Code of Conduct

- [x] I've read and agree to the [Code of Conduct](https://github.com/BarcelonaJS/organization/blob/main/code-of-conduct.md)

**Comment by onedesert** [comment]
Thanks! As soon as the talk is assigned to an event, we can e/meet an provide some feedback.

**Comment by imvenx** [comment]
> Hello! Could you present your talk next 25th at the January event? Thanks!

sure!

**Comment by imvenx** [comment]
So is confirmed? A few questions to refresh me, duration of the talk was about 25 min? Also should be all in english right?

> Hello! Could you present your talk next 25th at the January event? Thanks!

**Comment by onedesert** [comment]
You are the oldest summit, so if you agree it's confirmed. Talk duration should be 20 - 25 minutes, and yes everything is in english.

Please confirm again and I'll assign you to the event and publish it.

**Comment by imvenx** [comment]
confirmed

**Comment by onedesert** [comment]
thanks!

**Comment by imvenx** [comment]
@onedesert Hello, due to personal issues I can't assist to the event. I'm sorry and I hope you can find another speaker in time. Thanks for your understanding.

**Comment by onedesert** [comment]
@imvenx thanks for letting us know, we will try to find a speaker to cover.

**Comment by onedesert** [comment]
@imvenx as we have changed how we deal with issues, I'll close this one and ask you to resubmit into this new repo. I'll keep you in mind so we know you submitted early.
