### ISSUE TITLE
Event: December 2023

### ISSUE THREAD

**Issue by onedesert** [BarcelonaJS/events#46]
### Details

- Where: New Work Office Barcelona
- Address: Carrer del Consell de Cent, 334, 08009 Barcelona
- Sponsor: Honeypot & New Work SE
- When: 2023-12-20
- Hosts: @dmitry-zaets, @motanelu 
- Capacity: 40 pax. (50 minimum)

### Agenda

- BarcelonaJS & Sponsor Intro (5 min each)
- Talk 1 (25min): https://github.com/BarcelonaJS/events/issues/52
- Break
- Talk 2 (25min): https://github.com/BarcelonaJS/events/issues/36
- Social, food🍕 & drinks🧃!

### Sponsor Description

Honeypot is Europe’s leading tech job platform, on a mission to build great engineering teams. On Honeypot, you state your job preferences upfront and companies apply to you. We believe you should choose a job you love: whether that’s based on a cutting-edge tech stack, an inspiring team or just good old-fashioned salary.

### Code of Conduct

We expect everyone to uphold our
[Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/),
so please take a minute to read through it.

**Comment by onedesert** [comment]
https://github.com/BarcelonaJS/events/issues/35

**Comment by itziarmerladet** [comment]
Details
Where: New Work Office Barcelona
Address: Carrer del Consell de Cent, 334, 08009 Barcelona
Sponsor: Honeypot & New Work SE /
When: 2023-12-20
Hosts: @itziarmerladet 
Capacity: 40 people 
Agenda
BarcelonaJS & Sponsor Intro (5 min each)
Talk 1 (25min):
Break
Talk 2 (25min):
Social, food🍕 & drinks🧃!
Sponsor Description

Honeypot is Europe’s leading tech job platform, on a mission to build great engineering teams. On Honeypot, you state your job preferences upfront and companies apply to you. We believe you should choose a job you love: whether that’s based on a cutting-edge tech stack, an inspiring team or just good old-fashioned salary.

**Comment by onedesert** [comment]
@itziarmerladet we already have the community speaker assigned. Did your speaker already submit their talk?

**Comment by itziarmerladet** [comment]
I do not have a speaker yet, I need to check with the team if someone would be interested. What kind of topics should they prepare? 
If we do not manage to get a speaker, would you have someone else you can reach out to?

Thanks!

**Comment by itziarmerladet** [comment]
Hello, we have a speaker for the event: Kate Marshalkina 

Advent of Frontend Architecture
According to the State of JS report, the “Code Architecture” problem is the main pain point in frontend development. In this talk, we will connect the Software Architecture discipline with the modern frontend ecosystem.

**Comment by kalabro** [comment]
Thanks @itziarmerladet and @onedesert! I've just submitted it via GitHub issue to follow the process: https://github.com/BarcelonaJS/events/issues/52

**Comment by onedesert** [comment]
Thanks @kalabro and @itziarmerladet!
