### ISSUE TITLE
Event: January 2024

### ISSUE THREAD

**Issue by onedesert** [BarcelonaJS/events#47]
### Details

- Where: WeWork Paseo de Gracia
- Address: Passeig de Gràcia, 17, 08007 Barcelona (7th floor)
- Sponsor: Manychat / https://manychat.com/
- When: 2024-01-25
- Hosts: @onedesert , @dmitry-zaets 
- Capacity: 50 pax. (50 minimum)

### Agenda

- BarcelonaJS & Sponsor Intro (5 min each)
- Talk 1 (25min): https://github.com/BarcelonaJS/events/issues/48
- Break
- Talk 2 (25min): https://github.com/BarcelonaJS/events/issues/49
- Social, food🍕 & drinks🧃!

### Sponsor Description

Manychat is a leading Chat Marketing platform. Manychat enables businesses to drive more sales and conversions on messaging apps, such as Instagram, WhatsApp, Facebook Messenger, and Telegram, using automation.

With a global team of 140+ people located around three international offices — New York, Yerevan, and Barcelona, Manychat helps more than one million businesses worldwide interact with billions of customers in real-time at scale. 

### Code of Conduct

We expect everyone to uphold our
[Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/),
so please take a minute to read through it.

**Comment by onedesert** [comment]
Sponsor: https://github.com/BarcelonaJS/events/issues/42

**Comment by onedesert** [comment]
@meowsphere Please provide with a description of Manychat that we can use for the event description. Thanks!

Also let us know available dates for the last two weeks of January.

**Comment by meowsphere** [comment]
```
Manychat is a leading Chat Marketing platform. Manychat enables businesses to drive more sales and conversions on messaging apps, such as Instagram, WhatsApp, Facebook Messenger, and Telegram, using automation.

With a global team of 140+ people located around three international offices — New York, Yerevan, and Barcelona, Manychat helps more than one million businesses worldwide interact with billions of customers in real-time at scale. 
```

**Comment by meowsphere** [comment]
Hi! January 26-27 are free

**Comment by onedesert** [comment]
@meowsphere we have a speaker that will be at BCN between the 18th and 22nd https://github.com/BarcelonaJS/talks/issues/2 is there any option to have 22nd available? Thanks.

**Comment by meowsphere** [comment]
Hi @onedesert, is there any chance a speaker could stay until 23/24th? 22 is also available, I'm just not sure if Monday is OK for a meetup?

**Comment by onedesert** [comment]
As per his submission https://github.com/BarcelonaJS/talks/issues/2 he will be leaving the 23rd so 22nd is the last day. Regarding your concern about running an event on a Monday, it is not ideal, but should not be a problem.

**Comment by meowsphere** [comment]
OK, let's have it on Monday then.

**Comment by onedesert** [comment]
I have discussed with the rest of the organizers, as you mention, we believe that it will be better to host the event on Tuesday or Thursday. We have other community talk in line.

**Comment by meowsphere** [comment]
Scheduling on 25th of January then?

**Comment by onedesert** [comment]
Yeps!

**Comment by bouwe77** [comment]
Then I might submit my talk again someday in the future, might there be another occasion I'll be in Barcelona again 👍 https://github.com/BarcelonaJS/talks/issues/2

**Comment by onedesert** [comment]
Event ready, will prepare a draft soon and publish it to announce. @meowsphere on publish, we can sync to cross promote @ai or @dmitry-zaets will handle promotion from our side.

**Comment by onedesert** [comment]
@meowsphere event published -> https://www.meetup.com/barcelonajs/events/298503682/

**Comment by meowsphere** [comment]
@onedesert Hi! We will need a list of attendees with their real names and surnames for the security

**Comment by meowsphere** [comment]
@onedesert what do you need prepared for our side for video recording? Would you like to visit our office at the beginning of the next week in advance to see the space?

**Comment by onedesert** [comment]
I'll let @dmitry-zaets handle the video requirements as he is the expert.

The same day of the event i'll share the full list with you. By default we always request real name as is common on building security. Reach me out on LinkedIn so I can share it there privately.

**Comment by onedesert** [comment]
Previus speaker could not make it so we have new one https://github.com/BarcelonaJS/events/issues/49, will update the event and notify.
