### ISSUE TITLE
Talk Proposal: CI/CD observability for Frontend

### ISSUE THREAD

**Issue by meowsphere** [BarcelonaJS/events#48]
### Description

I’ll tell you why a front-end developer should think about CI/CD, and how these processes can be automated. In my talk, I will discuss why observability is needed, and what tools can be used for this.

### Details

- Speaker Name: Sergii Sergieiev
- Speaker Position: Manychat
- Speaker Company: Engineering Lead (Frontend)
- Speaker Twitter/Website: https://twitter.com/gurugray

### Code of Conduct

- [x] I've read and agree to the [Code of Conduct](https://github.com/BarcelonaJS/organization/blob/main/code-of-conduct.md)

**Comment by onedesert** [comment]
Thanks!
