### ISSUE TITLE
Talk Proposal: Mindful Leadership in Tech

### ISSUE THREAD

**Issue by nhowley** [BarcelonaJS/events#49]
www.tldrworkshops.com

### Description

Discover how cultivating self-awareness, emotional intelligence, and resilience can lead to improved decision-making, better team dynamics, enhanced soft skills, and increased well-being. Whether you're an aspiring tech leader or a seasoned executive, this talk will provide you with actionable insights to lead with presence, purpose, and compassion in the ever-evolving world of technology.

Around 20 minutes

### Details

- Speaker Name: Natalie Howley
- Speaker Position: Co-Founder and Wellbeing Coach at TL:DR, former Frontend Developer at One Beyond
- Speaker Company: TL;DR
- Speaker Twitter/Website: www.tldrworkshops.com

### Other

If you need help prepering the talk, please let us know.

### Code of Conduct

- [x] I've read and agree to the [Code of Conduct](https://github.com/BarcelonaJS/organization/blob/main/code-of-conduct.md)

**Comment by onedesert** [comment]
Hello! Could you present your talk next 25th at the January event? Thanks!

**Comment by nhowley** [comment]
Hi Yann,

Yes I can!

Thanks so much!

Have a lovely day,
Natalie

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by onedesert** [comment]
Hello! This month's talk is set, but your submission is queued for next month. We follow a first-come basis and the oldest already confirmed. Stay tuned!

**Comment by nhowley** [comment]
Ok, thank you for letting me know! So it's definitely confirmed for the February event or will I need to confirm again?

Thank you so much,
Natalie

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by onedesert** [comment]
Will need to confirm again, for every event we ask the old submits and the oldest to confirm is the one we assign. We plan to fix dates so maybe this procedure change next month

**Comment by nhowley** [comment]
Ok sounds good!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by onedesert** [comment]
@nhowley I know it is a short notice, but the current community speaker just informed us that he will not be able to make it for this January event on the 25th next week. 

Will you be ready? Thanks in advance.

**Comment by nhowley** [comment]
Great, I've just seen that the title of the talk is updated but the description is still the previous one 👀


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
