### ISSUE TITLE
Talk Proposal: Understand Your Data with Observable Plot

### ISSUE THREAD

**Issue by nachocab** [BarcelonaJS/events#51]
### Description

[Observable Plot](https://observablehq.com/plot) is a powerful JavaScript library that lets you extract useful insights from complex datasets without having to write a lot of code. Its API is concise, expressive and highly configurable. Once you learn the basics, you'll be able to explore your data from multiple directions and answer any kind of question with an elegant plot. 

To make it more engaging, you'll be able to follow along with an interactive Observable notebook so you can later attempt each plotting exercise on your own.

### Details

- Speaker Name: Nacho Caballero
- Speaker Position: Founder & CTO
- Speaker Company: Deliberate Spanish
- Speaker Twitter/Website: https://twitter.com/nachocaballero

### Other
I think this would work better as a 45 min workshop (half theory, half practice) than a 25 min talk, but I can adapt.

### Code of Conduct

- [x] I've read and agree to the [Code of Conduct](https://github.com/BarcelonaJS/organization/blob/main/code-of-conduct.md)

**Comment by dmitry-zaets** [comment]
Hi @nachocab,
Thank you for the submitted talk!
Unfortunately, at the moment, we accept only the talks and not the workshops. If you can reshape it to make a talk - that would be great.

**Comment by nachocab** [comment]
@dmitry-zaets Ok, no problem. Just remove the second paragraph from the description.

**Comment by nachocab** [comment]
I will no longer be able to present. Please retract my proposal
