### ISSUE TITLE
Event: May 2024

### ISSUE THREAD

**Issue by luisinnoit** [BarcelonaJS/events#58]
### Details

- Where: Aticco Verdaguer
- Address: C/ de Provença, 339, Barcelona
- Sponsor: InnoIT & Europcar.com / https://www.inno-it.es
- When: 2024-05-15
- Hosts: @Host1, @Host2
- Capacity: 80 pax. 

### Agenda

- BarcelonaJS & Sponsor Intro (5 min each)
- Talk 1 (25min): 
- Break
- Talk 2 (25min): 
- Social, food🍕 & drinks🧃!
- 
**We can add a speaker from our side.**

### Sponsor Description

We are a technology and digital native consultancy based in Spain, with more than 6 years of experience in projects and market team management covering the product development lifecycle and software/web solutions.
We build custom solutions for CEOs and CTOs of different business activities around the world. We are a team of 200 people located in Barcelona and Madrid, supporting more than 45 clients worldwide.

Services we are experts in:
•	Web Development
•	Infrastructure & DevOps
•	QA Testing & Test Automation
•	Big Data & Machine Learning
•	Methodologies: Agile, Lean, and Product Owner
•	Cybersecurity
•	Hybrid low-code projects
We also have a large Meetup community in Barcelona and Madrid, with more than 3,000 members and 90 organized tech meetups.

### Code of Conduct

We expect everyone to uphold our
[Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/),
so please take a minute to read through it.

**Comment by dmitry-zaets** [comment]
@luisinnoit Can you please create a Sponsor Request in https://github.com/BarcelonaJS/event-sponsors
