### ISSUE TITLE
Talk Proposal: Don't Forget React Memo

### ISSUE THREAD

**Issue by Croftyland** [BarcelonaJS/events#6]
### Description 

React developers intrigue us with the so-called React Forget compiler [that’s supposed to inject useMemo and useCallback into code automatically]. However, we still can't figure out best practices for useCallback, useMemo, and React.memo when we write it on our own. The worst scenario is if we continue to put it everywhere without understanding. As a result, it can bring noticeable harm to the performance of our application. In this talk, on real-life use cases, you will see solutions to the problem of using hooks wrong or overusing them!

It can last as 20min or 7min depends on you 🙂 

### Code of Conduct

- [x] I've read and agree to the
      [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by dmitry-zaets** [comment]
@Croftyland  Assigned to a December 2022 meetup a full talk 20-30min
