### ISSUE TITLE
Talk Proposal: Alice’s Adventures in Memoryland or how memory is managed in JavaScript 

### ISSUE THREAD

**Issue by krambertech** [BarcelonaJS/events#7]
Eventually the code we write becomes a bunch of 0s and 1s, and one day I went down the rabbit hole trying to understand how exactly that happens. Through JavaScript engine, heap, stack, garbage collection, references, memory addresses and so on. I found this really fascinating, so I want to share it with you in this visualised guide to memory management in JavaScript.

**🕑 Duration:** 30 minutes 

### Code of Conduct

- [x] I've read and agree to the
      [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by HusDev** [comment]
It was fun and great talk! I enjoyed and learned a lot.
